### ISSUE TITLE
Wrong error message when raising unsupported browser exception.

### ISSUE THREAD

**Issue by germaniumhq** [germaniumhq/germanium#1]
```
      Traceback (most recent call last):
        File "/home/raptor/programs/python-3.4.3/lib/python3.4/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/home/raptor/programs/python-3.4.3/lib/python3.4/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "steps/GermaniumSteps.py", line 144, in open_browser_impl
          create_germanium(browser, iframe_selector)
        File "steps/GermaniumSteps.py", line 90, in create_germanium
          raise ValueError('The browser should be something that exists: Firefox or Chrome, was `%s`', browser)
      ValueError: ('The browser should be something that exists: Firefox or Chrome, was `%s`', '1')
```

**Comment by germaniumhq** [comment]
Nor part of the `Germanium` code, but part of the actual test suite:
`File "steps/GermaniumSteps.py", line 90, in create_germanium`
