### ISSUE TITLE
NonIterable exception when iterating only over one Element

### ISSUE THREAD

**Issue by bmustiata** [germaniumhq/germanium#2]
```
      Traceback (most recent call last):
        File "/home/raptor/programs/python-3.4.3/lib/python3.4/site-packages/germanium/impl/wait.py", line 35, in wait
          if while_not_closure():
        File "/home/raptor/programs/python-3.4.3/lib/python3.4/site-packages/germanium/locators/DeferredLocator.py", line 13, in __call__
          return self.element_list()
        File "/home/raptor/programs/python-3.4.3/lib/python3.4/site-packages/germanium/locators/DeferredLocator.py", line 34, in element_list
          only_visible=only_visible)
        File "/home/raptor/programs/python-3.4.3/lib/python3.4/site-packages/germanium/impl/filter_not_displayed.py", line 27, in _filter_not_displayed
          result = list(filter(is_displayed_filter, found_items))
      TypeError: 'WebElement' object is not iterable
```

**Comment by germaniumhq** [comment]
From what I can tell WebDriver just decides to fire elements just because, and not a list. Made sure in case the result is a single WebElement, Germanium wraps it in a list.
